# Generated by Django 5.0.14 on 2025-11-27 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_tag_note_tags_tag_tags_user_id_eb4e0f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the entire conversation",
                        null=True,
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(
                        blank=True,
                        help_text="Condensed context for AI to understand the conversation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chats",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Full message content")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of this message (optional)",
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Approximate token count for this message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="notes.chat",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-last_message_at"], name="chats_user_id_6f7915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-created_at"], name="chats_user_id_e04d4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat", "created_at"], name="chat_messag_chat_id_012ed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat", "role"], name="chat_messag_chat_id_6775b5_idx"
            ),
        ),
    ]
